export const ActionTypes =  {
  CHOOSE_PERFORMANCE: 'CHOOSE_PERFORMANCE',
  CHOOSE_PLACE: 'CHOOSE_PLACE',
  CHOOSE_SHOW: 'CHOOSE_SHOW',
  CHOOSE_ITEM: 'CHOOSE_ITEM',
  GET_PERFORMANCES: 'GET_PERFORMANCES',
  GET_PLACES: 'GET_PLACES',
  GET_SHOWS: 'GET_SHOWS',
  MAKE_RESERVATION: 'MAKE_RESERVATION',
  RECEIVE_PERFORMANCES: 'RECEIVE_PERFORMANCES',
  RECEIVE_PLACES: 'RECEIVE_PLACES',
  RECEIVE_SHOWS: 'RECEIVE_SHOWS',
  RECEIVE_RESERVATION_RESPONCE: 'RECEIVE_RESERVATION_RESPONCE',
  RECEIVE_PRESCRIBED_DATA: 'RECEIVE_PRESCRIBED_DATA',
  NEXT_STAGE: 'NEXT_STAGE',
  PREVIOUS_STAGE: 'PREVIOUS_STAGE',
  CHANGE_FORM_DATA: 'CHANGE_FORM_DATA',
}

export const DocumentIds = {
  ROOT_ELEMENT: 'reservation-main',
  PRESCRIBED_DATA: 'reservation-prescribed-data',
}

