export const ActionTypes =  {
  CHOOSE_ITEM: 'CHOOSE_ITEM',
  MAKE_RESERVATION: 'MAKE_RESERVATION',
  RECEIVE_DATA: 'RECEIVE_DATA',
  RECEIVE_RESERVATION_RESPONCE: 'RECEIVE_RESERVATION_RESPONCE',
  RECEIVE_PRESCRIBED_DATA: 'RECEIVE_PRESCRIBED_DATA',
  NEXT_STAGE: 'NEXT_STAGE',
  PREVIOUS_STAGE: 'PREVIOUS_STAGE',
  CHANGE_FORM_DATA: 'CHANGE_FORM_DATA',
  FORM_VALIDATION: 'FORM_VALIDATION',
}

export const DocumentIds = {
  ROOT_ELEMENT: 'reservation-main',
  PREDEFINED_DATA: 'reservation-predefined-data',
}

